#!/usr/bin/env node
// YOLO dev launcher (M2) — idempotent one-command setup + run against the
// deepseek-harness dev host.
//
// Steps:
//   1. ensure host checkout (clone --depth 1 if missing)
//   2. install host deps (when node_modules missing)
//   3. build host artifacts (when apps/web/dist missing)
//   4. install YOLO deps (when node_modules missing — includes better-sqlite3
//      native binding, allowed via pnpm-workspace.yaml allowBuilds)
//   5. build YOLO artifacts (when dist/client/index.mjs missing — client bundle
//      discovery requires the built + wrapped client entry)
//   6. create the profile junction (~/.dsh/profiles/node_modules/dsh-plugin-yolo
//      -> repo root) so host resolves the package name to this repo
//   7. generate the runtime patch cordis.dev.local.yml (package-name entries:
//      bare name for the ClientModuleRegistry + per-plugin subpaths)
//   8. start `pnpm dsh web --patch <yml> --no-open --port <port>` in the host
//
// Options:
//   --setup   run steps 1-7 only (prepare, do not start)
//   --update  git pull the host first, then reinstall + rebuild, then start
//   --port N  custom port (default 4080 — 3080 is the running dsh GUI itself)

import { execFileSync, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const HOST = join(ROOT, 'host', 'deepseek-harness')
const HOST_REPO = 'https://github.com/deepseek-ai/deepseek-harness.git'
const PROFILE_DIR = join(homedir(), '.dsh', 'profiles')
const LINK_DIR = join(PROFILE_DIR, 'node_modules')
const LINK = join(LINK_DIR, 'dsh-plugin-yolo')
const PATCH = join(ROOT, 'cordis.dev.local.yml')
const PORT = parsePort()

function parsePort() {
  const i = process.argv.indexOf('--port')
  return i !== -1 && process.argv[i + 1] ? Number(process.argv[i + 1]) : 4080
}
const SETUP = process.argv.includes('--setup')
const UPDATE = process.argv.includes('--update')

const win = process.platform === 'win32'
const run = (cmd, args, cwd) => {
  const r = spawnSync(cmd, args, { cwd, stdio: 'inherit', shell: win && cmd === 'pnpm' })
  if (r.status !== 0) {
    console.error(`[dev] command failed: ${cmd} ${args.join(' ')} (exit ${r.status})`)
    if (win && cmd === 'pnpm') {
      console.error('[dev] tip: if this is the safe-delete trash error, run the command in PowerShell.')
    }
    process.exit(r.status ?? 1)
  }
}

const step = (n, label) => console.log(`\n[dev] step ${n}: ${label}`)

// 1. host checkout
step(1, 'host checkout')
if (!existsSync(join(HOST, 'package.json'))) {
  mkdirSync(join(ROOT, 'host'), { recursive: true })
  console.log('[dev] cloning deepseek-harness (shallow)...')
  execFileSync('git', ['clone', '--depth', '1', HOST_REPO, HOST], { stdio: 'inherit' })
} else {
  console.log('[dev] host checkout present')
  if (UPDATE) {
    console.log('[dev] git pull...')
    execFileSync('git', ['pull', '--ff-only'], { cwd: HOST, stdio: 'inherit' })
  }
}

// 2. host install
step(2, 'host deps')
if (!existsSync(join(HOST, 'node_modules'))) {
  run('pnpm', ['install'], HOST)
} else {
  console.log('[dev] host node_modules present')
}

// 3. host build
step(3, 'host build (web-app dist)')
if (!existsSync(join(HOST, 'apps', 'web', 'dist'))) {
  run('pnpm', ['run', 'build'], HOST)
} else {
  console.log('[dev] host dist present')
}

// 4. YOLO deps
step(4, 'YOLO deps')
if (!existsSync(join(ROOT, 'node_modules'))) {
  run('pnpm', ['install'], ROOT)
} else {
  console.log('[dev] YOLO node_modules present')
}

// 5. YOLO build (host plugins + wrapped client bundle)
step(5, 'YOLO build (client bundle)')
const hostEntries = ['src', 'storage', 'memory', 'extract', 'reminder', 'ui'].map((m) =>
  join(ROOT, 'dist', 'src', m, 'index.mjs'),
)
if (!existsSync(join(ROOT, 'dist', 'client', 'index.mjs')) || hostEntries.some((p) => !existsSync(p))) {
  run('pnpm', ['build'], ROOT)
} else {
  console.log('[dev] YOLO dist present')
}

// 6. profile junction — host resolves `dsh-plugin-yolo` from the profile's
//    node_modules; a Windows junction (no admin needed) keeps this repo live.
step(6, 'profile junction')
mkdirSync(LINK_DIR, { recursive: true })
if (existsSync(LINK)) rmSync(LINK, { recursive: true, force: true })
try {
  symlinkSync(ROOT, LINK, 'junction')
  console.log(`[dev] junction: ${LINK} -> ${ROOT}`)
} catch (e) {
  console.error(`[dev] junction failed: ${e.message}`)
  process.exit(1)
}

// 7. runtime patch — package-name entries (bare name for ClientModuleRegistry
//    discovery + per-plugin subpaths resolved via package.json exports)
step(7, 'runtime patch')
const patch = `# Generated by scripts/dev.mjs — do not edit.
- insert:
  - id: yolo
    name: dsh-plugin-yolo
  - id: yolo-storage
    name: dsh-plugin-yolo/dist/src/storage
  - id: yolo-memory
    name: dsh-plugin-yolo/dist/src/memory
  - id: yolo-extract
    name: dsh-plugin-yolo/dist/src/extract
  - id: yolo-reminder
    name: dsh-plugin-yolo/dist/src/reminder
  - id: yolo-ui
    name: dsh-plugin-yolo/dist/src/ui
`
writeFileSync(PATCH, patch)
console.log(`[dev] patch: ${PATCH}`)

if (SETUP) {
  console.log('\n[dev] setup complete. Start with: node scripts/dev.mjs')
  process.exit(0)
}

// 8. start
step(8, `start dsh web on :${PORT}`)
run('pnpm', ['dsh', 'web', '--patch', PATCH, '--no-open', '--port', String(PORT)], HOST)
