#!/usr/bin/env node
// YOLO end-to-end test runner (real host + Playwright).
//
//   node scripts/e2e.mjs              # ensure host up, then run all e2e specs
//   node scripts/e2e.mjs --spec panel # run one spec (tests/e2e/<spec>.spec.ts)
//   node scripts/e2e.mjs --no-host    # assume a host is already running
//
// The host pieces mirror scripts/dev.mjs (idempotent): ensure checkout, deps,
// build, junction + runtime patch, then `pnpm dsh web` on YOLO_E2E_PORT/4080.
// If a host already answers GET /yolo/dashboard we reuse it and skip bring-up
// (the common local case — dev.mjs left it running). We only stop a host this
// runner started, so a dev host the user owns is never killed.

import { execFileSync, spawn, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readlinkSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)))
const HOST = join(ROOT, 'host', 'deepseek-harness')
const HOST_REPO = 'https://github.com/deepseek-ai/deepseek-harness.git'
const PROFILE_DIR = join(homedir(), '.dsh', 'profiles')
const LINK_DIR = join(PROFILE_DIR, 'node_modules')
const LINK = join(LINK_DIR, 'dsh-plugin-yolo')
const PATCH = join(ROOT, 'cordis.dev.local.yml')
const PORT = Number(process.env.YOLO_E2E_PORT ?? process.env.PORT ?? 4080)
const BASE = `http://127.0.0.1:${PORT}`

const win = process.platform === 'win32'
const args = process.argv.slice(2)
const onlySpec = args.find((a) => a.startsWith('--spec='))?.split('=')[1]
const skipHost = args.includes('--no-host')

function childEnv() {
  const raw = process.env.NODE_OPTIONS ?? ''
  const cleaned = raw.replace(/--require=["'][^"']*genie-safe-delete[^"']*["']/g, '').trim()
  return { ...process.env, NODE_OPTIONS: cleaned }
}

function sleep(ms) {
  const e = Date.now() + ms
  while (Date.now() < e) { /* noop */ }
}

function hostUp() {
  try {
    // A host that answers with a 5xx (e.g. a stale dist missing a runtime asset)
    // is NOT usable — only treat a 2xx dashboard response as "up", so the runner
    // never silently reuses a broken host (the ready-wait loop also relies on this).
    execFileSync('node', ['-e', `
      const c = require('node:http').request('${BASE}/yolo/dashboard', r => {
        const ok = r.statusCode >= 200 && r.statusCode < 300;
        r.resume(); process.exit(ok ? 0 : 1)
      });
      c.on('error', () => process.exit(1)); c.setTimeout(3000, () => { c.destroy(); process.exit(1) }); c.end();
    `], { stdio: 'ignore', env: childEnv(), windowsHide: true })
    return true
  } catch {
    return false
  }
}

function run(cmd, argsList, opts = {}) {
  const r = spawnSync(cmd, argsList, {
    cwd: opts.cwd ?? ROOT,
    stdio: opts.silent ? 'ignore' : 'inherit',
    env: childEnv(),
    shell: win && cmd === 'pnpm',
  })
  return r.status ?? 1
}

function bringUpHost() {
  const step = (n, label) => console.log(`\n[e2e] step ${n}: ${label}`)

  step(1, 'host checkout')
  if (!existsSync(join(HOST, 'package.json'))) {
    mkdirSync(join(ROOT, 'host'), { recursive: true })
    execFileSync('git', ['clone', '--depth', '1', HOST_REPO, HOST], { stdio: 'inherit' })
  }

  step(2, 'host deps')
  if (!existsSync(join(HOST, 'node_modules'))) run('pnpm', ['install'], { cwd: HOST })

  step(3, 'host build')
  if (!existsSync(join(HOST, 'apps', 'web', 'dist'))) run('pnpm', ['run', 'build'], { cwd: HOST })

  step(4, 'YOLO deps')
  if (!existsSync(join(ROOT, 'node_modules'))) run('pnpm', ['install'])

  step(5, 'YOLO build (client bundle)')
  // A stale/incomplete dist (e.g. client bundle present but runtime assets like
  // schema.sql missing) silently breaks every dashboard query later, so rebuild
  // whenever any required artifact is absent rather than keying on index.mjs only.
  if (
    !existsSync(join(ROOT, 'dist', 'client', 'index.mjs')) ||
    !existsSync(join(ROOT, 'dist', 'src', 'storage', 'schema.sql'))
  ) run('pnpm', ['build'])

  step(6, 'profile junction')
  mkdirSync(LINK_DIR, { recursive: true })
  let ok = false
  try { ok = readlinkSync(LINK).toLowerCase() === ROOT.toLowerCase() } catch { ok = false }
  if (!ok) {
    if (existsSync(LINK)) {
      if (win) execFileSync('cmd', ['/c', 'rmdir', LINK])
      else rmSync(LINK, { recursive: true, force: true })
    }
    try { symlinkSync(ROOT, LINK, 'junction'); console.log(`[e2e] junction: ${LINK} -> ${ROOT}`) }
    catch (e) { console.error(`[e2e] junction failed: ${e.message}`); process.exit(1) }
  }

  step(7, 'runtime patch')
  writeFileSync(PATCH, `# Generated by scripts/e2e.mjs — do not edit.
- insert:
  - id: yolo
    name: dsh-plugin-yolo
  - id: yolo-storage
    name: dsh-plugin-yolo/dist/src/storage
  - id: yolo-memory
    name: dsh-plugin-yolo/dist/src/memory
  - id: yolo-extract
    name: dsh-plugin-yolo/dist/src/extract
  - id: yolo-reminder
    name: dsh-plugin-yolo/dist/src/reminder
  - id: yolo-ui
    name: dsh-plugin-yolo/dist/src/ui
`)

  step(8, `start dsh web on :${PORT}`)
  const child = spawn('pnpm', ['dsh', 'web', '--patch', PATCH, '--no-open', '--port', String(PORT)], {
    cwd: HOST, env: childEnv(), stdio: 'ignore', shell: win, detached: !win,
  })
  const deadline = Date.now() + 180_000
  while (Date.now() < deadline) {
    if (hostUp()) return child
    if (child.exitCode !== null || child.signalCode !== null) {
      console.error('[e2e] host process exited during bring-up')
      process.exit(1)
    }
    sleep(1500)
  }
  console.error(`[e2e] host did not become ready on ${BASE}`)
  try { child.kill() } catch {}
  process.exit(1)
}

;(async () => {
  let startedChild = null
  if (skipHost) {
    if (!hostUp()) { console.error(`[e2e] --no-host but nothing at ${BASE}/yolo/dashboard`); process.exit(1) }
    console.log(`[e2e] reusing running host at ${BASE} (--no-host)`)
  } else if (hostUp()) {
    console.log(`[e2e] reusing running host at ${BASE}`)
  } else {
    console.log(`[e2e] no host answering ${BASE} — bringing it up`)
    startedChild = bringUpHost()
  }

  const specArgs = onlySpec ? [join(ROOT, 'tests', 'e2e', `${onlySpec}.spec.ts`)] : []
  const code = run('pnpm', ['exec', 'playwright', 'test', ...specArgs], { cwd: ROOT })

  if (startedChild) {
    console.log('[e2e] stopping the host this runner started')
    try { startedChild.kill() } catch {}
  }
  process.exit(code ?? 0)
})()